"""add_invoices_daybook_gatepasses

Revision ID: 655ce31b133d
Revises: bc61f559f2ae
Create Date: 2026-05-23 03:50:41.153580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655ce31b133d'
down_revision: Union[str, Sequence[str], None] = 'bc61f559f2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
