"""gatepass_pdf_and_billing

Revision ID: 9b2adf6aad9d
Revises: 655ce31b133d
Create Date: 2026-05-23 04:39:50.691574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2adf6aad9d'
down_revision: Union[str, Sequence[str], None] = '655ce31b133d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
